--CREACION DE TABLAS

CREATE TABLE PERSONA(
IDPERSONA INT NOT NULL CONSTRAINT PK_PERSONA PRIMARY KEY,
TIPOPERSONAA VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDO VARCHAR2(50) NOT NULL,
SEXO VARCHAR2(10),
FECHANACIMIENTO VARCHAR2(50),
TELEFONO VARCHAR2(11),
DIRECCION VARCHAR2(50),
EMAIL VARCHAR2(50),
EDAD INT 
);

CREATE TABLE ALUMNO
(
IDALUMNO INT NOT NULL CONSTRAINT PK_ALUMNO PRIMARY KEY,
ESTADO VARCHAR2(50) NOT NULL,
IDAPODERADO INT,
CONSTRAINT FK_ALUMNO FOREIGN KEY (IDALUMNO) REFERENCES PERSONA(IDPERSONA),
CONSTRAINT FK_ALUMNO1 FOREIGN KEY (IDAPODERADO) REFERENCES PERSONA(IDPERSONA)
);

CREATE TABLE MAESTRO
(
IDMAESTRO INT NOT NULL,
ESPECIALIDAD VARCHAR2(50) NOT NULL,
SUELDO  NUMBER  NOT NULL,
ESTADO VARCHAR2(10) NOT NULL,
FECHAINGRESO VARCHAR2(50) NOT NULL,
CONSTRAINT PK_MAESTRO PRIMARY KEY (IDMAESTRO),
CONSTRAINT FK_MAESTRO FOREIGN KEY (IDMAESTRO) REFERENCES PERSONA(IDPERSONA)
);

CREATE TABLE GRADO
(
CODGRADO VARCHAR2(50) NOT NULL,
GRADO NUMBER NOT NULL,
NIVEL VARCHAR(50) NOT NULL,
PISO NUMBER NOT NULL,
CONSTRAINT PK_GRADO PRIMARY KEY (CODGRADO)
);

CREATE TABLE ASIGNATURA
(
CODASIGNATURA VARCHAR2(50) NOT NULL,
NOMB_ASIGNATURA VARCHAR(50) NOT NULL,
CONSTRAINT  PK_ASIGNATURA PRIMARY KEY (CODASIGNATURA)
);

CREATE TABLE GRADO_ASIGNATURA
(
CODGRADO VARCHAR2(50) NOT NULL,
CODASIGNATURA VARCHAR2(50) NOT NULL,
CONSTRAINT FK_GRADO FOREIGN KEY (CODGRADO) REFERENCES GRADO(CODGRADO),
CONSTRAINT FK_ASIGNATURA FOREIGN KEY (CODASIGNATURA) REFERENCES ASIGNATURA(CODASIGNATURA)
);

CREATE TABLE MAESTRO_ASIGNATURA
(
IDMAESTRO INT NOT NULL,
CODASIGNATURA VARCHAR2(50) NOT NULL,
ESTADO VARCHAR2(50) NOT NULL,
AÑOACADEMICO VARCHAR2(50) NOT NULL,
CONSTRAINT FK_MAESTRO_ASIGNATURA FOREIGN KEY (IDMAESTRO) REFERENCES MAESTRO(IDMAESTRO),
CONSTRAINT FK_MAESTRO_ASIGNATURA1 FOREIGN KEY (CODASIGNATURA) REFERENCES ASIGNATURA(CODASIGNATURA)
);

CREATE TABLE NOTAS
(
IDALUMNO INT NOT NULL,
CODASIGNATURA VARCHAR2(50) NOT NULL,
PC1 DECIMAL(4,2),
PC2 DECIMAL(4,2),
PC3 DECIMAL(4,2),
EX_MENSUAL DECIMAL(4,2),
EX_BIMESTRAL  DECIMAL(4,2),
CONSTRAINT FK_NOTAS FOREIGN KEY (CODASIGNATURA) REFERENCES ASIGNATURA(CODASIGNATURA),
CONSTRAINT FK_NOTAS1 FOREIGN  KEY (IDALUMNO) REFERENCES ALUMNO(IDALUMNO)
);



--INSERTAR DATOS

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(1,'AL','ANDRES','FERIA','MASCULINO','18/04/2002',NULL,'AV CERRO LOMAS','AFERIA@gmail.com',16);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(2,'AL','ANDREY','VALDEZ','MASCULINO','07/03/2002',NULL,'AV 1RO DE  MAYO','AVALDEZ@gmail.com',16);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(3,'AL','FLOR','GOMEZ','FEMENINO','07/09/2002',NULL,'AV LA ENCANTADA','FGOMEZ@gmail.com',16);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(4,'AL','BRYAN','RAMOS','MASCULINO','17/09/2002',NULL,'AV MALVINAS','BRAMOS@gmail.com',16);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5,'AL','JOSEPH','MARTINEZ','MASCULINO','27/11/2002',NULL,'AV ZARATE','JMARTINEZ@gmail.com',16);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(6,'AL','ANTONY','MANDUJANO','MASCULINO','27/03/2003',NULL,'AV LA C','AMANDUJANO@gmail.com',15);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(7,'AL','ISRAEL','RAMOS','MASCULINO','18/10/2003',NULL,'AV DIANA','IRAMOS@gmail.com',15);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(8,'AL','JUNIOR','OCHOAA','MASCULINO','01/10/2003',NULL,'AV ROJOS','JOCHOA@gmail.com',15);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(9,'AL','MIGUEL','HUAMAN','MASCULINON','01/01/2003',NULL,'AV PROCERES','MHUAMAN@gmail.com',15);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(10,'AL','CAMILA','GARCIA','FEMENINO','21/1/2003',NULL,'LOS CUBANOS','CGARCIA@gmail.com',15);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(11,'AL','CAMILA','GARCIA','FEMENINO','21/1/2004',NULL,'LOSS CUBANOS','CGARCIA@gmail.com',14);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(12,'AL','MARIA','RAMOS','FEMENINO','22/10/2004',NULL,'SEC1  GRP1 MAZB LT101','MRAMOS@gmail.com',14);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(13,'AL','KIMBERLY','HURTADO','FEMENINO','23/09/2004',NULL,'SEC3  GRP1 MAZB LT10','KHURTADO@gmail.com',14);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(14,'AL','JESENIA','HURTADO','FEMENINO','28/09/2004',NULL,'SEC10  GRP1 MAZA LT10','JHURTADO@gmail.com',14);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(15,'AL','MARTIN','HORNA','MASCULINO','28/12/2004',NULL,'COMAS','MHORNA@gmail.com',14);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(16,'AL','ANYELA','INCA','FEMENINO','05/02/2005',NULL,'SC3 GRP11 MAZG LT14','AINCA@gmail.com',13);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(17,'AL','MADELINE','ACUÑA','FEMENINO','12/06/2005',NULL,'TABLADA /SEGUNDA ZONA','MACUÑA@gmail.com',13);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(18,'AL','SOFIA','MOLINA','FEMENINO','07/12/2005',NULL,'TALARA RUTA LA C','SSMOLINA@gmail.com',13);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(19,'AL','LUZMILA','HUAMAN','FEMENINO','04/12/2005',NULL,'ASOC LAS  MALVINAS','LHUAMAN@gmail.com',13);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(20,'AL','LEYLA','FERIA','FEMENINO','12/04/2005',NULL,'COND PATIO UNION','LFERIA@gmail.com',13);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(21,'AL','ANGELITO','SALAZAR','MASCULINO','12/09/2006',NULL,'ASOC LAS PALMERAS','ASALAZAR@gmail.com',12);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(22,'AL','CARLOS','MORENO','MASCULINO','12/11/2006',NULL,'ASOC MI CASA','CMORENO@gmail.com',12);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(23,'AL','EDGAR','TORRES','MASCULINO','09/11/2006',NULL,'COND PALOMAS','ETORRES@gmail.com',12);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(24,'AL','LUIS','RODRIGUEZ','MASCULINO','09/08/2006',NULL,'COND PALMAS','LRODRIGUEZ@gmail.com',12);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(25,'AL','PAULINA','BARRETO','FEMENINO','28/06/2006',NULL,'LAS CASORINAS','PBARRETO@gmail.com',12);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(26,'AL','GERSON','NAPA','MASCULINO','09/01/2007',NULL,'ASOC PALMAS','GNAPA@gmail.com',11);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(27,'AL','KARINA','DIAZ','FEMENINO','02/02/2007',NULL,'ASOC LA MOLINA','KDIAZ@gmail.com',11);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(28,'AL','LIZI','HUANCACURI','FEMENINO','03/03/2007',NULL,'ASOC HACIENDA','LHUANQK@gmail.com',11);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(29,'AL','ANABEL','QUISPE','FEMENINO','20/02/2007',NULL,'ASOC EL HUECO','AQUISPE@gmail.com',11);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(30,'AL','RUBEN','CUADROS','MASCULINO','21/02/2007',NULL,'ASOC VILLA','RCUADROS@gmail.com',11);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(31,'AL','JUAN','TITO','MASCULINO','22/02/2008',NULL,'ASOC DESIERTO','JTITO@gmail.com',10);


INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(32,'AL','JOSHUA','OBREGON','MASCULINO','12/05/2008',NULL,'ASOC BARRANCA','JOBREGON@gmail.com',10);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(33,'AL','FIORELA','ROJAS','FEMENINO','07/11/2008',NULL,'ASOC SAN JORGE','FROJAS@gmail.com',10);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(34,'AL','DAYANA','MENDOZA','FEMENINO','13/05/2008',NULL,'ASOC MI CASA','DMENDOZA@gmail.com',10);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(35,'AL','GIANPIER','DELGADO','MASCULINO','11/12/2008',NULL,'ASOC FERREIROS','GDELGADO@gmail.com',10);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(36,'AL','JHONATAN','GALLARDO','MASCULINO','01/12/2009',NULL,'ASOC TALARA','JGALLARDO@gmail.com',9);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(37,'AL','JOSE','GARCIA','MASCULINO','01/10/2009',NULL,'ASOC LA FLECHA','JGARCIA@gmail.com',9);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(38,'AL','DANTE','QUISPE','MASCULINO','01/05/2009',NULL,'ASOC NUEVO MUNDO','DQUISPE@gmail.com',9);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(39,'AL','JEAMPIER','LEON','MASCULINO','11/05/2009',NULL,'ASOC PESQUERO','JLEON@gmail.com',9);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(40,'AL','CARLOS','PANTA','MASCULINO','11/05/2009',NULL,'ASOC PESQUERO','CPANTA@gmail.com',9);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(41,'AL','VALERY','PANTA','FEMENINO','10/05/2010',NULL,'TALARA LA C','VPANTA@gmail.com',8);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(42,'AL','BRENDA','GUZMAN','FEMENINO','10/11/2010',NULL,'AV ARRIBA PERU','BGUZMAN@gmail.com',8);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(43,'AL','DIEGO','GUZMAN','MASCULINO','08/01/2010',NULL,'AV ARRIBA PERU','DGUZMAN@gmail.com',8);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(44,'AL','GERSON','QUITO','MASCULINO','28/07/2010',NULL,'AV BRISAS','GQUITO@gmail.com',8);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(45,'AL','NICK','CARRASCO','MASCULINO','28/10/2010',NULL,'AV RUTA B','NCARRASCO@gmail.com',8);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(46,'AL','PIER','URBINA','MASCULINO','28/10/2011',NULL,'AV ALIPIO','PURBINA@gmail.com',7);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(47,'AL','LUIS','RODRIGUEZ','MASCULINO','18/10/2011',NULL,'AV LURIN','LRODRIGUEZ@gmail.com',7);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(48,'AL','LUIS','QUISPE','MASCULINO','18/01/2011',NULL,'AV MAGDALENA','LQUISPE@gmail.com',7);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(49,'AL','ALVARO','ROSAS','MASCULINO','08/11/2011',NULL,'AV REYNOSO','AROSAS@gmail.com',7);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(50,'AL','JEAN','ROJAS','MASCULINO','08/12/2011',NULL,'AV DUEÑAS','JROJAS@gmail.com',7);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(51,'AL','JOAQUIN','MENDOZA','MASCULINO','01/12/2012',NULL,'AV UNIVERSITARIA','JMENDOZA@gmail.com',6);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(52,'AL','JEFFERSON','HURTADO','MASCULINO','01/11/2012',NULL,'AV OLAYA','JHURTADO@gmail.com',6);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(53,'AL','ALEX','MENDOZA','MASCULINO','01/08/2012',NULL,'AV MARIATEGUI','AMENDOZA@gmail.com',6);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(54,'AL','JOSE','CUENCA','MASCULINO','11/08/2012',NULL,'AV VALLEJO','JCUENCA@gmail.com',6);
INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(55,'AL','KEVIN','QUISPE','MASCULINO','14/09/2012',NULL,'AV SOL','KQUISPE@gmail.com',6);



SELECT  *  FROM PERSONA ORDER BY  IDPERSONA;

--------INSERT APODERADOS--------------
INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1001,'AP','ABRAHAN','FERIA','980567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1002,'AP','LUCIA','VALDEZ','991175524');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1003,'AP','TALY','GOMEZ','991075524');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1004,'AP','CARLOS','RAMOS','980567599');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1005,'AP','PEPE','MARTINEZ','980567588');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1006,'AP','TERRY','MANDUJANO','980567577');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1007,'AP','JANET','RAMOS','980567566');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1008,'AP','DAVID','OCHOA','980567555');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1009,'AP','ESAUD','HUAMAN','980567544');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1010,'AP','DARWIN','GARCIA','980567533');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1011,'AP','ROSARIO','GARCIA','980567522');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1012,'AP','GIOVANNA','RAMOS','980567511');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1013,'AP','LUCIA','HURTADO','980567500');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1014,'AP','EVA','HURTADO','988567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1015,'AP','NICANOR','HORNA','989567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1016,'AP','MAURICIA','INCA','987567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1017,'AP','MILAGROS','ACUÑA','986567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1018,'AP','EDERR','MOLINA','985567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1019,'AP','ROBERTO','HUAMAN','984567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1020,'AP','LUZ','FERIA','983567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1021,'AP','JOSTIN','SALAZAR','982567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1022,'AP','RUTH','MORENO','981567546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1023,'AP','MARTIN','TORRES','980167546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1024,'AP','JULIO','RODRIGUEZ','980267546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1025,'AP','TATIANA','BARRETO','980367546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1026,'AP','ANTONIO','NAPA','980467546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1027,'AP','LUIS','DIAZ','980667546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1028,'AP','JOSE','HUANCACURI','980767546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1029,'AP','ANDRES','QUISPE','980867546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1030,'AP','YSRAEL','CUADROS','980967546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1031,'AP','FELIX','TITO','980517546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1032,'AP','MANUEL','OBREGON','980527546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1033,'AP','MARILUZ','ROJAS','980537546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1034,'AP','TOÑITA','MENDOZA','980547546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1035,'AP','PAOLA','DELGADO','980557546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1036,'AP','MAYDITH','GALLARDO','980587546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1037,'AP','JUDITH','GARCIA','980597546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1038,'AP','PAMELA','QUISPE','980507546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1039,'AP','NANCY','LEON','980561546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1040,'AP','MITZY','PANTA','980562546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1041,'AP','LAURA','PANTA','980563546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1042,'AP','SAMANTA','GUZMAN','980564546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1043,'AP','SHEILA','GUZMAN','980565546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1044,'AP','NORMA','QUITO','980566546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1045,'AP','FLOR','CARRASCO','980568546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1046,'AP','STEFANY','URBINA','980569546');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1047,'AP','EDGAR','RODRIGUEZ','980567146');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1048,'AP','RODRIGO','QUISPE','980567246');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1049,'AP','GUSTAVO','ROSAS','980567346');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1050,'AP','DANNY','ROJAS','980567346');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1051,'AP','SERGIO','MENDOZA','980567446');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1052,'AP','SANTI','HURTADO','980567646');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1053,'AP','SHERMAN','MENDOZA','980567746');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1054,'AP','MIGUEL','CUENCA','980567846');

INSERT INTO PERSONA(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,TELEFONO) 
VALUES (1055,'AP','ANA','QUISPE','980567946');

-----INSERTAR EN LA TABLA ALUMNOS------

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (1,'ACTIVO',1001);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (2,'ACTIVO',1002);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (3,'ACTIVO',1003);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (4,'ACTIVO',1004);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (5,'ACTIVO',1005);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (6,'ACTIVO',1006);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (7,'ACTIVO',1007);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (8,'ACTIVO',1008);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (9,'ACTIVO',1009);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (10,'INACTIVO',1010);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (11,'ACTIVO',1011);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (12,'ACTIVO',1012);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (13,'ACTIVO',1013);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (14,'ACTIVO',1014);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (15,'ACTIVO',1015);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (16,'INACTIVO',1016);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (17,'ACTIVO',1017);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (18,'ACTIVO',1018);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (19,'ACTIVO',1019);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (20,'ACTIVO',1020);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (21,'ACTIVO',1021);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (22,'ACTIVO',1022);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (23,'INACTIVO',1023);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (24,'ACTIVO',1024);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (25,'ACTIVO',1025);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (26,'ACTIVO',1026);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (27,'ACTIVO',1027);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (28,'ACTIVO',1028);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (29,'ACTIVO',1029);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (30,'ACTIVO',1030);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (31,'ACTIVO',1031);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (32,'ACTIVO',1032);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (33,'ACTIVO',1033);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (34,'ACTIVO',1034);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (35,'ACTIVO',1035);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (36,'ACTIVO',1036);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (37,'ACTIVO',1037);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (38,'ACTIVO',1038);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (39,'INACTIVO',1039);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (40,'ACTIVO',1040);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (41,'ACTIVO',1041);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (42,'ACTIVO',1042);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (43,'ACTIVO',1043);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (44,'INACTIVO',1044);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (45,'ACTIVO',1045);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (46,'ACTIVO',1046);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (47,'ACTIVO',1047);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (48,'ACTIVO',1048);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (49,'INACTIVO',1049);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (50,'INACTIVO',1050);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (51,'ACTIVO',1051);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (52,'ACTIVO',1052);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (53,'ACTIVO',1053);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (54,'ACTIVO',1054);

INSERT INTO ALUMNO(IDALUMNO,ESTADO,IDAPODERADO) 
VALUES (55,'ACTIVO',1055);


--PROFESORES ACTIVOS------------------

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5001,'MA','DEYANIRA','MEDRANO','FEMENINO','01/12/1980','965874213','AV UNIVERSITARIA','MAJMEDRANO@gmail.com',38);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5002,'MA','OLENKA','GARCIA','FEMENINO','03/10/1979','965874233','AV DUEÑAS','MAOGARCIA@gmail.com',39);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5003,'MA','ANGELA','FLORES','FEMENINO','01/01/1978','965874243','AV ALIPIO','MAAFLORES@gmail.com',40);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5004,'MA','LAYLA','ARANA','FEMENINO','21/97/1978','965874113','AV SOL','MALARANA@gmail.com',40);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5005,'MA','RAUL','PEREZ','MASCULINO','31/10/1980','965574213','AV DIANA','MARPEREZ@gmail.com',38);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5006,'MA','JOSE','ROSARIO','MASCULINO','01/03/1978','961874213','AV BRISAS','MAJROSARIO@gmail.com',40);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5007,'MA','LUIS','ROJAS','MASCULINO','05/11/1996','965874219','AV LOS ROJOS','MALROJAS@gmail.com',22);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5008,'MA','JORGE','RIVASPLATA','MASCULINO','18/04/1990','985874213','AV PALOMAS','MAJRIVASPLATA@gmail.com',28);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5009,'MA','JULIO','OLAYA','MASCULINO','01/12/1980','969894213','AV CHEPEN','MAJOLAYA@gmail.com',38);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5010,'MA','JHON','CALVO','MASCULINO','01/12/1978','965874299','AV OASIS','MAJCALVO@gmail.com',40);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5011,'MA','DIANA','MENDOZA','FEMENINO','14/09/1996','965874203','AV LA PARADA','MADMENDOZA@gmail.com',22);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5012,'MA','DANTE','MIRANDA','MASCULINO','16/02/1980','965874213','AV PALOMAS','MADMIRANDA@gmail.com',38);

INSERT INTO PERSONA
(IDPERSONA,TIPOPERSONAA,NOMBRE,APELLIDO,SEXO,
FECHANACIMIENTO,TELEFONO,DIRECCION,EMAIL,EDAD)
VALUES
(5013,'MA','JAVIER','FLORES','MASCULINO','14/04/1978','965879913','AV TABLADA','MAFMASCULINO@gmail.com',40);

--PROFESORES ACTIVOS

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5001,'Docente',1400,'Activo','05/03/2018');
--DEYANIRA MEDRANO 1er grado

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5002,'Docente',1400,'Activo','05/03/2018');
--OLENKA GARCIA 2DO grado

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5003,'Docente',1400,'Activo','05/03/2018');
--ANGELA FLORES 3er grado

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5004,'Docente',1400,'Activo','05/03/2018');
--LAYLA ARANA 4TO grado

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5005,'Docente',1400,'Activo','05/03/2018');
--RAUL PEREZ 5TO grado

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5006,'Idiomas',1000,'Activo','05/03/2018');
--JOSE ROSARIO INGLES

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5007,'Informatica',1400,'Activo','05/03/2018');
--LUIS ROJAS computacion

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5008,'Deporte',1200,'Activo','05/03/2018');
--JORGE RIVASPLATA ED. FISICA

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5009,'Matematica',1300,'Activo','05/03/2018');
--JULIO OLAYA 

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5010,'Matematica',1300,'Activo','05/03/2018');
--JHON CALVO

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5011,'Ciencias Naturales',1350,'Activo','05/03/2018');
--Diana Mendoza

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5012,'Comunicacion',1350,'Activo','05/03/2018');
--DANTE MIRANDA

insert into maestro (idmaestro,especialidad,SUELDO,estado,fechaingreso) 
values (5013,'Ciencias Sociales',1350,'Activo','05/03/2018');
--JAVIER FLORES

--ASIGNATURAS 

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG01','Comunicacion');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG02','Matematica');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG03','Personal Social');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG04','Ciencia Y Tecnologia');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG05','Religion');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG06','EducFisica');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG07','Arte');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG08','Computacion');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG09','Ingles');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG10','Aritmetica');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG11','Geometria');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG12','Trigonometria');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG13','Lenguaje');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG14','Literatura');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG15','Biologia');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG16','Quimica');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG17','Civica');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG18','Fisica');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG19','Geografia');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG20','Historia');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG21','Algebra');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG22','Razonamiento Verbal');

insert into asignatura (codasignatura,nomb_asignatura)
values ('ASIG23','Razonamiento Matematico');



--GRADOS

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0001',1,'PRIMARIA',1);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0002',2,'PRIMARIA','1');

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0003',3,'PRIMARIA',2);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0004',4,'PRIMARIA',2);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0005',5,'PRIMARIA',2);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0006',6,'PRIMARIA',3);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0007',1,'SECUNDARIA',3);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0008',2,'SECUNDARIA',3);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0009',3,'SECUNDARIA',3);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0010',4,'SECUNDARIA',3);

INSERT INTO GRADO(CODGRADO,GRADO,NIVEL,PISO)
VALUES ('GR0011',5,'SECUNDARIA',3);

--GRADOS ASIGNATURAS

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG01');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG01');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG01');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG01');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG01');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG02');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG02');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG02');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG02');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG02');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG03');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG03');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG03');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG03');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG03');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG04');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG04');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG04');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG04');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG04');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG05');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG05');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG05');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG05');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG05');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG07');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG07');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG07');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG07');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG07');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0001','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0002','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0003','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0004','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0005','ASIG09');

--SECUNDARIA
INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG10');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG11');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG12');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG13');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG14');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG15');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG16');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG17');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG18');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG19');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG20');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG21');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG22');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0006','ASIG23');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG10');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG11');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG12');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG13');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG14');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG15');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG16');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG17');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG18');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG19');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG20');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG21');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG22');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0007','ASIG23');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG10');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG11');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG12');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG13');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG14');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG15');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG16');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG17');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG18');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG19');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG20');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG21');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG22');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0008','ASIG23');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG10');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG11');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG12');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG13');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG14');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG15');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG16');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG17');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG18');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG19');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG20');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG21');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG22');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0009','ASIG23');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG10');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG11');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG12');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG13');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG14');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG15');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG16');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG17');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG18');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG19');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG20');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG21');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG22');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0010','ASIG23');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG06');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG08');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG09');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG10');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG11');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG12');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG13');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG14');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG15');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG16');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG17');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG18');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG19');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG20');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG21');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG22');

INSERT INTO GRADO_ASIGNATURA(CODGRADO,CODASIGNATURA)
VALUES ('GR0011','ASIG23');


--ASIGNATURAS POR MAESTRO

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5001,'ASIG01','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5001,'ASIG02','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5001,'ASIG03','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5001,'ASIG04','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5001,'ASIG05','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5001,'ASIG07','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5002,'ASIG01','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5002,'ASIG02','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5002,'ASIG03','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5002,'ASIG04','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5002,'ASIG05','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5002,'ASIG07','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5003,'ASIG01','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5003,'ASIG02','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5003,'ASIG03','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5003,'ASIG04','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5003,'ASIG05','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5003,'ASIG07','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5004,'ASIG01','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5004,'ASIG02','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5004,'ASIG03','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5004,'ASIG04','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5004,'ASIG05','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5004,'ASIG07','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5005,'ASIG01','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5005,'ASIG02','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5005,'ASIG03','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5005,'ASIG04','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5005,'ASIG05','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5005,'ASIG07','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5006,'ASIG09','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5007,'ASIG08','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5008,'ASIG06','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5009,'ASIG10','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5009,'ASIG21','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5009,'ASIG23','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5010,'ASIG11','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5010,'ASIG12','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5010,'ASIG18','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5011,'ASIG15','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5011,'ASIG16','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5012,'ASIG13','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5012,'ASIG14','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5012,'ASIG22','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5013,'ASIG17','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5013,'ASIG19','ACTIVO','2018');

INSERT INTO maestro_asignatura(IDMAESTRO,CODASIGNATURA,ESTADO,AÑOACADEMICO)
VALUES (5013,'ASIG20','ACTIVO','2018');

--NOTAS

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (26,'ASIG08',14.00,11.50,7.00,5.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (26,'ASIG09',14.00,10.50,7.00,18.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (26,'ASIG10',14.00,11.50,17.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (26,'ASIG11',14.00,11.50,7.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (26,'ASIG12',14.00,11.50,17.00,8.00,10.00);
--------------------------------------------------------------

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (27,'ASIG08',14.00,11.50,7.00,5.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (27,'ASIG09',14.00,11.50,7.00,18.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (27,'ASIG10',14.00,11.50,7.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (27,'ASIG11',14.00,10.50,7.00,18.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (27,'ASIG12',14.00,11.50,17.00,18.00,11.00);
   
-----------------------------------------------
   
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (28,'ASIG08',14.00,11.50,7.00,15.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (28,'ASIG09',14.00,10.50,7.00,8.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (28,'ASIG10',4.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (28,'ASIG11',14.00,11.50,7.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (28,'ASIG12',14.00,11.50,7.00,8.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (29,'ASIG08',14.00,11.50,17.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (29,'ASIG09',14.00,10.50,17.001,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (29,'ASIG10',14.00,11.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (29,'ASIG11',14.00,11.50,7.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (29,'ASIG12',14.00,11.50,7.00,8.00,11.00);

---------------------------------------------------------

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (30,'ASIG08',4.00,11.50,7.00,15.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (30,'ASIG09',14.00,1.50,7.00,8.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (30,'ASIG10',4.00,11.50,7.00,8.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (30,'ASIG11',4.00,1.50,7.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (30,'ASIG12',14.00,11.50,7.00,8.00,1.00);

---------------------------------------------------------

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (31,'ASIG06',4.00,11.50,17.00,15.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (31,'ASIG07',14.00,1.50,17.00,8.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (31,'ASIG08',4.00,11.50,7.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (31,'ASIG09',4.00,1.50,7.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (31,'ASIG10',14.00,11.50,17.00,8.00,1.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (32,'ASIG06',4.00,11.50,17.00,5.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (32,'ASIG07',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (32,'ASIG08',4.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (32,'ASIG09',4.00,11.50,7.00,18.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (32,'ASIG10',14.00,11.50,17.00,8.00,1.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (33,'ASIG06',4.00,11.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (33,'ASIG07',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (33,'ASIG08',4.00,11.50,17.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (33,'ASIG09',4.00,11.50,7.00,18.00,12.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (33,'ASIG10',14.00,11.50,17.00,8.00,20.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (34,'ASIG06',4.00,11.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (34,'ASIG07',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (34,'ASIG08',4.00,11.50,17.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (34,'ASIG09',4.00,11.50,7.00,18.00,12.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (34,'ASIG10',14.00,11.50,17.00,8.00,20.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (35,'ASIG06',4.00,11.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (35,'ASIG07',14.00,11.50,7.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (35,'ASIG08',14.00,11.50,17.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (35,'ASIG09',4.00,11.50,7.00,18.00,12.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (35,'ASIG10',14.00,11.50,7.00,8.00,2.00);

---------------------------------------------------------

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (36,'ASIG05',4.00,11.50,17.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (36,'ASIG06',4.00,1.50,7.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (36,'ASIG07',14.00,11.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (36,'ASIG08',4.00,11.50,7.00,18.00,12.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (37,'ASIG05',14.00,11.50,17.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (37,'ASIG06',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (37,'ASIG07',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (37,'ASIG08',4.00,11.50,17.00,18.00,12.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (38,'ASIG05',14.00,1.50,17.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (38,'ASIG06',14.00,11.50,7.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (38,'ASIG07',14.00,1.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (38,'ASIG08',4.00,11.50,7.00,18.00,2.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (39,'ASIG05',14.00,1.50,17.00,5.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (39,'ASIG06',4.00,11.50,7.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (39,'ASIG07',14.00,1.50,7.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (39,'ASIG08',4.00,11.50,7.00,18.00,2.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (40,'ASIG05',14.00,1.50,17.00,5.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (40,'ASIG06',4.00,11.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (40,'ASIG07',14.00,1.50,7.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (40,'ASIG08',4.00,11.50,17.00,18.00,2.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (41,'ASIG03',14.00,1.50,17.00,5.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (41,'ASIG04',4.00,11.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (41,'ASIG05',14.00,1.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (42,'ASIG03',14.00,1.50,17.00,15.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (42,'ASIG04',14.00,11.50,17.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (42,'ASIG05',14.00,1.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (43,'ASIG03',14.00,1.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (43,'ASIG04',4.00,11.50,7.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (43,'ASIG05',14.00,1.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (44,'ASIG03',14.00,1.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (44,'ASIG04',14.00,11.50,17.00,8.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (44,'ASIG05',14.00,1.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (45,'ASIG03',14.00,1.50,17.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (45,'ASIG04',14.00,11.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (45,'ASIG05',14.00,1.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (45,'ASIG02',14.00,1.50,17.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (45,'ASIG03',14.00,11.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (45,'ASIG04',14.00,1.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (46,'ASIG02',14.00,11.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (46,'ASIG03',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (46,'ASIG04',14.00,11.50,7.00,18.00,11.00);



---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (47,'ASIG02',4.00,11.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (47,'ASIG03',14.00,1.50,17.00,8.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (47,'ASIG04',14.00,11.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (48,'ASIG02',4.00,11.50,17.00,5.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (48,'ASIG03',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (48,'ASIG04',14.00,11.50,7.00,18.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (49,'ASIG02',14.00,11.50,17.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (49,'ASIG03',14.00,11.50,17.00,18.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (49,'ASIG04',14.00,11.50,7.00,8.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (50,'ASIG02',14.00,11.50,7.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (50,'ASIG03',14.00,1.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (50,'ASIG04',14.00,11.50,17.00,8.00,11.00);

---------------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (51,'ASIG01',14.00,11.50,7.00,15.00,11.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (51,'ASIG02',14.00,1.50,17.00,18.00,1.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (51,'ASIG03',14.00,11.50,17.00,8.00,11.00);

--------------------------------------------------
INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (52,'ASIG01',10.00,12.50,9.00,10.00,20.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (52,'ASIG02',10.00,14.50,1.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (52,'ASIG03',12.00,13.50,8.00,8.00,20.00);



--------------------------------------------------------------

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (53,'ASIG01',10.00,10.50,19.00,10.00,2.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (53,'ASIG02',11.00,17.50,11.00,18.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (53,'ASIG03',14.00,16.50,18.00,18.00,10.00);

--------------------------------------------------------------


INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (54,'ASIG01',11.00,10.50,19.00,10.00,2.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (54,'ASIG02',12.00,17.50,11.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (54,'ASIG03',14.00,13.50,8.00,18.00,0.00);


--------------------------------------------------------------

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (55,'ASIG01',11.00,10.50,19.00,10.00,2.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (55,'ASIG02',12.00,17.50,11.00,8.00,10.00);

INSERT INTO NOTAS(IDALUMNO,CODASIGNATURA,PC1,PC2,PC3,EX_MENSUAL,EX_BIMESTRAL) 
VALUES (55,'ASIG03',14.00,3.50,8.00,18.00,0.00);
