--1. CONSULTAR LOS CLIENTES QUE TIENEN CORREO GMAIL
SELECT * FROM PRODUCCION.CLIENTE WHERE LOWER(TRIM(CLI_EMAIL)) LIKE '%gmail.com';

--2. CONSULTAR LOS CLIENTES QUE REGISTRAN TELÉFONO
SELECT * FROM PRODUCCION.CLIENTE WHERE TELEFONO IS NULL OR TRIM(TELEFONO) = '';

--3. CONSULTAR LOS CLIENTES QUE LA TERCERA LETRA DE SU NOMBRE PUEDE SER A, O, ó R
SELECT * FROM PRODUCCION.CLIENTE WHERE SUBSTR(UPPER(TRIM(CLI_NOMBRE)),3,1) = 'A' OR 
SUBSTR(UPPER(TRIM(CLI_NOMBRE)),3,1) = 'O' OR SUBSTR(UPPER(TRIM(CLI_NOMBRE)),3,1) = 'R';

--4. CONSULTAR LOS CLIENTES MUJERES QUE SU CORREO ELECTÓNICO CONTENGA AL MENOS UN APELLIDO
SELECT * FROM PRODUCCION.CLIENTE WHERE CLI_SEXO = 'F' AND
 (UPPER(CLI_EMAIL)  LIKE '%'||CLI_APELLIDOPAT||'%' OR UPPER(CLI_EMAIL)  LIKE '%'||CLI_APELLIDOMAT||'%'); 

--5. CONSULTAR LOS CLIENTES QUE REGISTRAN NUMERO DE CELULAR
SELECT * FROM PRODUCCION.CLIENTE WHERE LENGTH(TRIM(TELEFONO)) = 9;

--6. CONSULTAR LAS FACTURA QUE SE EMITIERON POR EL CONSUMO EN EL SEGUNDO PISO
SELECT IDMESA FROM PRODUCCION.MESA	WHERE UPPER(TRIM(UBICACION)) LIKE '%SEGUNDO PISO%';

SELECT * FROM PRODUCCION.FACTURA WHERE IDMESA IN (
(SELECT IDMESA FROM PRODUCCION.MESA	WHERE 
	UPPER(TRIM(UBICACION)) LIKE '%SEGUNDO PISO%')
);

--7. CONSULTAR LA CANTIDAD DE PLATOS QUE SE ATENDIO POR  MOZO 
SELECT F.IDMOZO, M.MOZ_NOMBRE, COUNT(F.IDMOZO) AS cantidad  
FROM PRODUCCION.FACTURA F 
JOIN PRODUCCION.MOZO M ON F.IDMOZO = M.IDMOZO
GROUP BY F.IDMOZO, M.MOZ_NOMBRE;
 
--8. CONSULTAR LA CANTIDAD DE FACTURAS QUE SE EMITIEROS POR DIA

SELECT TO_CHAR(F.FECHAFACTURA,'DD/MM/YYYY') "FECHA", COUNT(F.FECHAFACTURA) "CANTIDAD DE FACTURAS"
FROM PRODUCCION.FACTURA F 
JOIN PRODUCCION.DETALLEFACTURA D
ON F.IDFACTURA = D.IDFACTURA
GROUP BY TO_CHAR(F.FECHAFACTURA,'DD/MM/YYYY');

--9  CONSULTAR CUANTAS VECES SE HA ATENDIDO EL PLATO ARROZ CON POLLO EL ULTIMO DIA
SELECT COUNT(*) AS "CANT. ARROZ C/ POLLO -ULT. DIA"
FROM PRODUCCION.FACTURA F 
JOIN PRODUCCION.DETALLEFACTURA D
ON F.IDFACTURA = D.IDFACTURA
WHERE 
EXTRACT(YEAR FROM F.FECHAFACTURA) = (SELECT MAX(EXTRACT(YEAR FROM FECHAFACTURA)) FROM PRODUCCION.FACTURA) AND
EXTRACT(MONTH FROM F.FECHAFACTURA) = (SELECT MAX(EXTRACT(MONTH FROM FECHAFACTURA)) FROM PRODUCCION.FACTURA) AND
EXTRACT(DAY FROM F.FECHAFACTURA) = (SELECT MAX(EXTRACT(DAY FROM FECHAFACTURA)) FROM PRODUCCION.FACTURA) AND
D.IDPLATO = (SELECT IDPLATO FROM PRODUCCION.PLATO WHERE NOMBREPLATO LIKE UPPER(TRIM('%ARROZ%')));



--10 CONSULTAR LA CANTIDAD DE PLATOS QUE SE ATENDIO POR COCINERO
SELECT IDCOCINERO "COCINERO", COUNT(*) "CANTIDAD DE PLATOS" 
FROM PRODUCCION.DETALLEFACTURA
GROUP BY IDCOCINERO;


--11 CONSULTAR LOS PLATOS QUE SE CONSUMIERON MAYORES A 1 VEZ EL ULTIMO MES
SELECT D.IDPLATO, COUNT(D.IDPLATO)
FROM PRODUCCION.FACTURA F
JOIN PRODUCCION.DETALLEFACTURA D
ON F.IDFACTURA = D.IDFACTURA
WHERE
EXTRACT(YEAR FROM F.FECHAFACTURA) = (SELECT MAX(EXTRACT(YEAR FROM FECHAFACTURA)) FROM PRODUCCION.FACTURA) AND
EXTRACT(MONTH FROM F.FECHAFACTURA) = (SELECT MAX(EXTRACT(MONTH FROM FECHAFACTURA)) FROM PRODUCCION.FACTURA) 
GROUP BY D.IDPLATO
HAVING COUNT(1)>1;

--12 CONSULTAR EL CLIENTE QUE MAS VECES A CONSUMIDO
WITH 
C AS (	
	SELECT IDCLIENTE IDCLI, COUNT(1) CANT 
		FROM PRODUCCION.FACTURA 
	GROUP BY IDCLIENTE
	
)
SELECT IDCLI CLIENTE,CANT "CANT. ATENCIONES"
FROM C
WHERE CANT = (SELECT MAX(CANT) 
                   FROM C);

--13 CONSULTAR QUE MOZO ATENDIO EL PLATO TALLARINES EL ULTIMO MES
SELECT F.IDMOZO, M.MOZ_NOMBRE  
FROM PRODUCCION.FACTURA F 
JOIN PRODUCCION.MOZO M ON F.IDMOZO = M.IDMOZO
JOIN PRODUCCION.DETALLEFACTURA D ON F.IDFACTURA = D.IDFACTURA 
WHERE
EXTRACT(YEAR FROM F.FECHAFACTURA) = (SELECT MAX(EXTRACT(YEAR FROM FECHAFACTURA)) FROM PRODUCCION.FACTURA) AND
EXTRACT(MONTH FROM F.FECHAFACTURA) = (SELECT MAX(EXTRACT(MONTH FROM FECHAFACTURA)) FROM PRODUCCION.FACTURA)
AND D.IDPLATO = (SELECT IDPLATO FROM PRODUCCION.PLATO WHERE NOMBREPLATO = UPPER(TRIM('TALLARINES')) )


--14 CONSULTAR EL PLATO MAS REQUERIDO POR LOS CLIENTES VARONES

SELECT P.IDPLATO,P.NOMBREPLATO
FROM PRODUCCION.CLIENTE C
INNER JOIN PRODUCCION.FACTURA  F ON F.IDCLIENTE = C.IDCLIENTE
INNER JOIN PRODUCCION.DETALLEFACTURA DF ON DF.IDFACTURA = F.IDFACTURA
INNER JOIN PRODUCCION.PLATO P ON P.IDPLATO = DF.IDPLATO 
WHERE C.CLI_SEXO = 'M'
AND DF.IDPLATO IN (SELECT MAX(IDPLATO)  
				FROM (SELECT IDPLATO , COUNT(IDPLATO) AS CANT_X_PLATO 
					  FROM PRODUCCION.DETALLEFACTURA GROUP BY IDPLATO))
GROUP BY P.IDPLATO,P.NOMBREPLATO ;

--15 CONSULTAR QUE PLATOS SE HAN CONSUMIDO EL ULTIMO DIA

SELECT P.IDPLATO, P.NOMBREPLATO, TO_CHAR(F.FECHAFACTURA,'DD-MON-YYYY') ULTIMO_DIA
FROM PRODUCCION.PLATO P 
INNER JOIN PRODUCCION.DETALLEFACTURA DF ON DF.IDPLATO = P.IDPLATO
INNER JOIN PRODUCCION.FACTURA F ON F.IDFACTURA = DF.IDFACTURA
WHERE F.FECHAFACTURA IN (
SELECT MAX(FECHAFACTURA) FECHA_FACTURA FROM PRODUCCION.FACTURA);

--16 INSERTAR DATOS EN TABLA FACTURA DE TAL MANERA QUE SU ID SE GENERE SEQUECIALMENTE
 
-- Cargar Datos
CREATE SEQUENCE SQ_FACTURA
INCREMENT BY 1
START WITH 2000;

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'1','1','1',to_date('06/11/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'2','2','1',to_date('03/09/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'3','3','2',to_date('06/11/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'1','4','3',to_date('12/08/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'5','4','3',to_date('06/11/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'6','2','5',to_date('16/10/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'1','3','3',to_date('16/10/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'8','1','7',to_date('06/11/2018','DD/MM/YYYY'));

INSERT INTO FACTURA(IdFactura,IdCliente,IdMozo,IdMesa,FechaFactura)
VALUES(SQ_FACTURA.NEXTVAL,'8','2','3',to_date('26/10/2018','DD/MM/YYYY'));
commit;