
SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE
FROM SCOTT.EMP E, SCOTT.SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL


SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE
FROM SCOTT.EMP E CROSS JOIN SCOTT.SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL


SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE
FROM SCOTT.EMP E INNER JOIN SCOTT.SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL