-- MODIFICANDO VALORES
CREATE TABLE RECURSOS.DEP_01 AS (SELECT * FROM RECURSOS.DEPARTAMENTO)
INSERT INTO RECURSOS.DEP_01 (IDDEPARTAMENTO, NOMBRE, IDUBICACION) SELECT  * FROM RECURSOS.DEPARTAMENTO WHERE IDDEPARTAMENTO = 107;