
---SUB CONSULTA CORRELACIONADA O RECURSIVA


CREATE TABLE TEST
(
ID CHAR(5) PRIMARY KEY,
NAME VARCHAR2(20),
SALARY NUMBER(8,2)	
)

DROP TABLE TEST

INSERT INTO RECURSOS.TEST(ID,NAME,SALARY) 
SELECT IDEMPLEADO,NOMBRE,SUELDO  FROM RECURSOS.EMPLEADO 
WHERE IDDEPARTAMENTO=102;


SELECT * FROM RECURSOS.TEST
