-- TAREA CINCO INSERT ALL

CREATE TABLE SCOTT.TEST50 AS (SELECT * FROM SCOTT.DEPT WHERE 1=0)

CREATE TABLE SCOTT.TEST80 AS (SELECT * FROM SCOTT.DEPT WHERE 1=0)

CREATE TABLE SCOTT.TEST AS (SELECT * FROM SCOTT.DEPT WHERE 1=0)


INSERT ALL 
	WHEN  DEPTNO = 30 THEN 
		INTO SCOTT.TEST50 (DEPTNO, DNAME, LOC)
		VALUES(DEPTNO, DNAME, LOC)
	WHEN DEPTNO = 40 THEN
		INTO SCOTT.TEST80 (DEPTNO, DNAME, LOC)
		VALUES(DEPTNO, DNAME, LOC)
	ELSE
		INTO SCOTT.TEST (DEPTNO, DNAME, LOC)
		VALUES(DEPTNO, DNAME, LOC)
	SELECT  DEPTNO, DNAME, LOC 
	FROM SCOTT.DEPT;
	