

insert into RECURSOS.test (id, name, salary)
select 'S' || EMPNO, ENAME, SAL
from SCOTT.EMP;

SELECT * FROM RECURSOS.TEST;

COMMIT;


CREATE PUBLIC DATABASE LINK LNK_GRACIELA 
CONNECT TO SYSTEM IDENTIFIED BY oracle
USING '172.17.2.149:1521/ORCL';

SELECT * FROM SCOTT.EMP@LNK_GRACIELA;

SELECT * FROM RECURSOS.EMPLEADO@LNK_GRACIELA;





